### ISSUE TITLE
Face detection is loaded on video assets

### ISSUE THREAD

**Issue by nathansmonk** [interconnectit/my-eyes-are-up-here#12]
If for example, you have video assets in the media library and you bring up the edit screen for the asset, the face detection still loads, and you get broken images with an infinitely spinning spinner.

It's not really a problem, because you can just ignore it, but for those who aren't in the know it seems a bit confusing.

**Comment by davecoveney** [comment]
Thanks - will fix that on the next release!

**Comment by nathansmonk** [comment]
Woo! Just seen this is fixed in the latest release - I was gonna submit a PR this weekend too! Thanks.

**Comment by davecoveney** [comment]
Glad to make you happy :-)
