### ISSUE TITLE
plugin breaks media admin on WP 4.4

### ISSUE THREAD

**Issue by carletto0282** [interconnectit/my-eyes-are-up-here#15]

**Comment by raldenhoven** [comment]
I already made a pull request(https://github.com/interconnectit/my-eyes-are-up-here/pull/14) with a fix

**Comment by carletto0282** [comment]
Ok thanks

**Comment by davecoveney** [comment]
I've merged pull request #14 into the plugin - any tests would be nice!

**Comment by carletto0282** [comment]
It works fine for me
